Yasmeen166/team member page UI
UBC-VCL/VCL-content-platform pull request #126
Opened 2023-09-23 04:08 UTC by yasmeen45

## Description

Changed background colour for team member page and hid "add member" button if user is not logged in.
## Updates

Changed background colour in team member page css and added conditional render for "add member" button.

## Checklist

- [ ] Ran `npm run lint:fix` to format code
- [ ] Requested at least one reviewer
- [ ] Connected PR to Trello ticket (steps below)
- [ ] Addressed code review comments
- [ ] Gained at least one approval for your PR

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown.

2023-09-23 04:09 UTC, yasmeen45 commented
![](https://github.trello.services/images/mini-trello-icon.png) [team member page ui, hide add member button if not log in](https://trello.com/c/shyqvIkB/166-team-member-page-ui-hide-add-member-button-if-not-log-in)

2023-09-24 03:56 UTC, ryanyae requested changes
Everything looks good to me. But I was wondering if you were able to fix this gap at the bottom of the page? 
![image](https://github.com/UBC-VCL/VCL-content-platform/assets/76890786/dfbf05e8-d6c7-4dd4-9d1f-70d1d4ec27c7)

2023-09-24 03:56 UTC, ryanyae commented on src/pages/Project/ProjectTeam.tsx
> -                    <Person
I think you can just take all of these comments out tbh.

2023-09-24 03:56 UTC, ryanyae commented on src/pages/Project/ProjectTeam.tsx
> -            {/* <div className="team-header">Team Members</div>
You can this out as well.

2023-09-24 20:44 UTC, yasmeen45 commented
Done! Gap was fixed and commented out code was already deleted I believe

2023-09-24 23:12 UTC, ryanyae commented
Ah yes you are completely right, sorry about that

2023-09-24 23:13 UTC, ryanyae approved these changes

2023-09-24 23:13 UTC, ryanyae approved these changes

2023-09-24 23:14 UTC, merged