#176 make past projects more dynamic
UBC-VCL/VCL-content-platform pull request #138
Opened 2023-10-10 21:59 UTC by OttoChen312

## Description

uncommented the past projects code in the projectjoin class
created a object in the project interface for pastprojects with a title and a description 
added the pastprojects property to each project object in projectwrapper

## Updates

[Please enter a brief summary of updates to this PR during code review - if any]

## Checklist

- [ ] Ran `npm run lint:fix` to format code
- [ ] Requested at least one reviewer
- [ ] Connected PR to Trello ticket (steps below)
- [ ] Addressed code review comments
- [ ] Gained at least one approval for your PR

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown.

2023-10-10 21:59 UTC, OttoChen312 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Make past projects dynamic](https://trello.com/c/QRLvPd3R/176-make-past-projects-dynamic)

2023-10-12 05:17 UTC, ryanyae requested changes
Thank you Otto! All this looks great!

2023-10-12 05:17 UTC, ryanyae commented on src/pages/Project/ProjectJoin.tsx
> +                    {props.project.pastProjects?.map(items =>
Just one request, can you just add padding to the individual past projects? 
![image](https://github.com/UBC-VCL/VCL-content-platform/assets/76890786/3b186f18-5024-4a54-b3ea-42e47953f3a6)

2023-10-12 19:08 UTC, ElisaHu1 commented
also there is a conflict file @OttoChen312 if you could modify it

2023-10-13 18:19 UTC, ryanyae requested changes
Just resolve the conflicts and I will be able to merge this into main!

2023-10-13 18:19 UTC, ryanyae commented on src/pages/Project/ProjectJoin.tsx
> +                    {props.project.pastProjects?.map(items =>
Do you think you could also adding padding to the left and the right?

2023-10-15 02:50 UTC, ElisaHu1 approved these changes
looks great!

2023-10-15 02:55 UTC, ryanyae approved these changes
Sorry for keep this PR blocked but great job Otto! Thank you for your hard work!

2023-10-15 02:55 UTC, merged