188 rename supervisors to management
UBC-VCL/VCL-content-platform pull request #150
Opened 2023-11-16 11:00 UTC by OttoChen312

## Description

[Please enter a brief description of the PR]

## Updates

[Please enter a brief summary of updates to this PR during code review - if any]

## Checklist

- [ ] Ran `npm run lint:fix` to format code
- [ ] Requested at least one reviewer
- [ ] Connected PR to Trello ticket (steps below)
- [ ] Addressed code review comments
- [ ] Gained at least one approval for your PR

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown.

2023-11-16 11:04 UTC, OttoChen312 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Consistency in capitalization across website](https://trello.com/c/J5QBZlc3/190-consistency-in-capitalization-across-website)

2023-11-16 11:04 UTC, OttoChen312 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Rename supervisors to management](https://trello.com/c/32c2llYS/188-rename-supervisors-to-management)

2023-11-17 05:42 UTC, ElisaHu1 commented
@OttoChen312 there is a conflict file, can you update that?

2023-11-18 04:48 UTC, ElisaHu1 commented
@OttoChen312 you failed the linting lol

2023-11-18 04:57 UTC, OttoChen312 commented
Oh sorry I changed it on GitHub, I should have changed on Intelliji, I will implement the changes through Intelliji.

2023-11-18 05:00 UTC, OttoChen312 commented
I will review the conflicts on Intelliji by tonight sorry about that

2023-11-20 02:21 UTC, ElisaHu1 approved these changes
looks good to me! waiting for @ryanyae to review it

2023-11-21 18:57 UTC, ryanyae requested changes
Just address the 2 comments I left, besides that everything else looks good to me, good job Otto!

2023-11-21 18:57 UTC, ryanyae commented on src/pages/People/People.tsx
> +                    return item.position === 'Lab Manager' || item.position === 'Lab Leader' || item.position === 'Assistant Lab Manager and Workshop Coordinator' || item.position === 'Workshop Coord
When comparing 2 strings with "===", the equality behaviour will be case-sensitive. This is very nit-picky, but I think it's better to have a non-case-sensitive implementation to ensure we are not filtering out typos.

2023-11-21 18:57 UTC, ryanyae commented on src/pages/People/People.tsx
> +                        return item.position === 'Lab Manager' || item.position === 'Lab Leader' || item.position === 'Assistant Lab Manager and Workshop Coordinator' || item.position === 'Workshop C
Same thing here with case-sensitivity.

2023-11-26 18:35 UTC, ryanyae requested changes
Everything else looks great, just address my comments and we can merge this.

2023-11-26 18:35 UTC, ryanyae commented on src/pages/People/People.tsx
> +                    return item.position.toLowerCase() == 'Lab Manager'.toLowerCase() || item.position.toLowerCase() == 'Lab Leader'.toLowerCase() || item.position.toLowerCase() == 'Assistant Lab Man
Converting all these to lower case is actually redundant and not necessary, when using "==" its not case sensitive so "ADasd" will equal "adasd". So I think taking it out is for the best.

2023-11-26 18:35 UTC, ryanyae commented on src/pages/People/People.tsx
> +                        return item.position.toLowerCase() == 'Lab Manager'.toLowerCase() || item.position.toLowerCase() == 'Lab Leader'.toLowerCase() || item.position.toLowerCase() == 'Assistant Lab
same thing here.

2023-12-15 21:06 UTC, ryanyae approved these changes

2023-12-15 21:07 UTC, merged