Connorwon 226 mobile view v2 sidebar
UBC-VCL/VCL-content-platform pull request #168
Opened 2024-02-20 02:12 UTC by ConnorWon

## Description

Made sidebar stick to top for projectsV2 mobile view

## Updates

added a state in redux which tracks if user is viewing the projectsV2 pages
made nav bar box shadow change depending on if in projectsV2 pages

## Checklist

- [ ] Ran `npm run lint:fix` to format code
- [ ] Requested at least one reviewer
- [ ] Connected PR to Trello ticket (steps below)
- [ ] Addressed code review comments
- [ ] Gained at least one approval for your PR

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown.

2024-02-20 02:13 UTC, ConnorWon commented
![](https://github.trello.services/images/mini-trello-icon.png) [mobile view v2 sidebar](https://trello.com/c/7wa29JO3/226-mobile-view-v2-sidebar)

2024-02-20 22:46 UTC, ryanyae requested changes
Great job! I just have the one requested change and could you maybe change the colour for mobile view because the desktop navbar is white but the mobile navbar is like a gray, 
![image](https://github.com/UBC-VCL/VCL-content-platform/assets/76890786/154f101d-2eeb-4ba3-99f1-8ca3ba5bc66c)
.

2024-02-20 22:46 UTC, ryanyae commented on src/pages/ProjectV2/Wrapper/ProjectV2Wrapper.css
> +        font-weight: bold;
Maybe just a little bit heavier? I don't know the default weight of a bold text but maybe around 700-800?

2024-02-21 04:53 UTC, ConnorWon commented on src/pages/ProjectV2/Wrapper/ProjectV2Wrapper.css
> +        font-weight: bold;
Done. Had to change the import for Open Sans in App.css

2024-02-21 05:38 UTC, ElisaHu1 approved these changes
this looks awesome!
thank you for your hardwork Connor!

2024-02-22 01:55 UTC, ryanyae approved these changes

2024-02-22 01:55 UTC, merged