Fix line spacing
UBC-VCL/VCL-content-platform pull request #172
Opened 2024-03-06 05:35 UTC by tjachu

## Description

- Home page line spacing changes (landing page & contact info) 
- "Who is this for?" card components, fix width and center icon

## Updates

[Please enter a brief summary of updates to this PR during code review - if any]

## Checklist

- [ ] Ran `npm run lint:fix` to format code
- [ ] Requested at least one reviewer
- [ ] Connected PR to Trello ticket (steps below)
- [ ] Addressed code review comments
- [ ] Gained at least one approval for your PR

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown.

2024-03-07 01:52 UTC, ElisaHu1 commented on package-lock.json
you do not need to add the change of package-lock.json

2024-03-07 18:16 UTC, ryanyae requested changes
I think having the line-height values for all of the text may be the best option. Besides, the two comments that I had left, great work on the ticket.

2024-03-07 18:16 UTC, ryanyae commented on src/components/LandingPage/LandingPage.css
> +  line-height: 20px;
I think we can just take this line of code out and the other "line-height:1.2" to completely fix this issue, as I am still seeing a little bit of over lap still. 
![image](https://github.com/UBC-VCL/VCL-content-platform/assets/76890786/2c467865-e9f4-4263-b0d2-6afc3a561bc6)

2024-03-07 18:16 UTC, ryanyae commented on src/components/About/About.css
> +  line-height: 22px;
Taking this piece of code out aswell will take the overlapping of text. (Image for the change you have as of now) 
![image](https://github.com/UBC-VCL/VCL-content-platform/assets/76890786/2e87371a-10d3-4e91-8115-46ef12562d03)

2024-03-11 18:19 UTC, ElisaHu1 approved these changes
looks great!

2024-03-11 20:51 UTC, ryanyae approved these changes
Looks good to me, thank you Allison!

2024-03-11 20:51 UTC, merged