Finished the Affiliations page
UBC-VCL/VCL-content-platform pull request #182
Opened 2024-03-28 00:02 UTC by MuzammilC

## Description

This PR involves the development of the affiliations page for the website.

## Updates

[Please enter a brief summary of updates to this PR during code review - if any]

## Checklist

- [ * ] Ran `npm run lint:fix` to format code
- [ * ] Requested at least one reviewer
- [ * ]  Connected PR to Trello ticket (steps below)
- [ ] Addressed code review comments
- [ ] Gained at least one approval for your PR

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown.

2024-03-28 00:57 UTC, MuzammilC commented
![](https://github.trello.services/images/mini-trello-icon.png) [affiliated lab page (mobile view + tablet view + pc)](https://trello.com/c/MPyEoZNN/211-affiliated-lab-page-mobile-view-tablet-view-pc)

2024-03-28 01:01 UTC, ElisaHu1 approved these changes
looks great! just linting issue

2024-03-28 01:01 UTC, ElisaHu1 commented on src/statics/affiliations.ts
> +                    href: "http://perception.yale.edu.s3-website-us-east-1.amazonaws.com/",
change this to https://perception.yale.edu/

2024-04-01 03:53 UTC, ryanyae requested changes
Sorry for the late review, but the only thing I would like a tweak of is adding max widths to the page, adding this will allow people with really large monitors to just look at the middle of their screen instead of having to map through their entire screen.

2024-04-04 00:46 UTC, ryanyae commented
@MuzammilC Now that you have implemented the max-width you would have to account for this scenario
![image](https://github.com/UBC-VCL/VCL-content-platform/assets/76890786/cdacf60f-7eb0-4ed1-9a42-3f7ed0b7f082)

2024-04-04 09:10 UTC, MuzammilC commented
The above issues should be fixed now, I also added a breakpoint for the width property of affiliations nav so that it looks cleaner on bigger screens.

2024-04-05 05:06 UTC, ryanyae approved these changes
Looks good to me, thank you Muzammil!

2024-04-05 05:07 UTC, merged