Ryanyae 235 edit timeline fix frontend
UBC-VCL/VCL-content-platform pull request #186
Opened 2024-04-08 18:59 UTC by ryanyae

## Description

Fixed the frontend for timeline edit/add bugs

## Updates

[Please enter a brief summary of updates to this PR during code review - if any]

## Checklist

- [ ] Ran `npm run lint:fix` to format code
- [ ] Requested at least one reviewer
- [ ] Connected PR to Trello ticket (steps below)
- [ ] Addressed code review comments
- [ ] Gained at least one approval for your PR

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown.

2024-04-10 21:02 UTC, ElisaHu1 commented
the ui looks wired lol, what are the save button for? 
<img width="614" alt="image" src="https://github.com/UBC-VCL/VCL-content-platform/assets/104804980/44d06529-0d18-4a58-9393-790a508f58e9">

2024-04-13 04:04 UTC, ElisaHu1 approved these changes

2024-04-13 04:06 UTC, ElisaHu1 commented
need to work on ui ticket later

2024-04-14 22:30 UTC, ConnorWon requested changes

2024-04-16 02:13 UTC, ConnorWon commented on src/pages/Timeline/EditTimelineEntry/EditTimelineEntry.tsx
> +          author: currUser.username.replace(/['"]+/g, ''),
EditTimeline page isn't working anymore and I think it may be because of this line

2024-04-16 03:39 UTC, ryanyae commented on src/pages/Timeline/EditTimelineEntry/EditTimelineEntry.tsx
> +          author: currUser.username.replace(/['"]+/g, ''),
Oh sorry, I wanted to spend a little longer with the code before requesting for reviews again. I'll let you know when I am done

2024-04-16 03:40 UTC, ConnorWon commented on src/pages/Timeline/EditTimelineEntry/EditTimelineEntry.tsx
> +          author: currUser.username.replace(/['"]+/g, ''),
Oh shoot that's mb

2024-04-25 04:38 UTC, ConnorWon reviewed
Looking good just one thing.
1. When I try to edit a timeline entry, the Description textarea isn't pre-populated. Also, it doesn't seem to get updated after saving my changes

https://github.com/UBC-VCL/VCL-content-platform/assets/120760211/f5629afa-ef59-407a-a9c3-789fe6e866e9

2024-04-26 05:47 UTC, ConnorWon commented
There still seems to be a small problem with the description in EditTimelineEntry. If you create a description that includes '\n':
1.  When you open EditTimeline for that entry the description is displayed as a comma-separated list
2. Also, you can't seem to update the entry if you don't change the description


https://github.com/UBC-VCL/VCL-content-platform/assets/120760211/fb8e93c5-ce78-4a45-8f67-74ad99ce8fcc

2024-05-02 06:15 UTC, ConnorWon commented
Sorry to keep nitpicking, but the links for the timeline entry now have an issue when it doesn't start with "https://".
I believe you can fix that if you add a conditional similar to this:
![Screenshot 2024-05-01 at 11 09 24 PM](https://github.com/UBC-VCL/VCL-content-platform/assets/120760211/6d3bb763-d060-4adf-829b-a095f754ffe3)

2024-05-02 17:08 UTC, ryanyae commented
> Sorry to keep nitpicking, but the links for the timeline entry now have an issue when it doesn't start with "https://". I believe you can fix that if you add a conditional similar to this: ![Screenshot 2024-05-01 at 11 09 24 PM](https://private-user-images.githubusercontent.com/120760211/327326945-6d3bb763-d060-4adf-829b-a095f754ffe3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2Njk5NjUsIm5iZiI6MTcxNDY2OTY2NSwicGF0aCI6Ii8xMjA3NjAyMTEvMzI3MzI2OTQ1LTZkM2JiNzYzLWQwNjAtNGFkZi04MjliLWEwOTVmNzU0ZmZlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQxNzA3NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYmFlMWEzMzY2OGJhOTU3YTlmNWE2N2FjY2Q0ODQyYTdkMTUxMzk5ZmNlMTk1ODM1YjRlNDQ4OWEzZjI4NzQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gKiLLCoZj5TBJ7P7ViiTGtJNLw1RD6mzPxUtneFoznA)

Yea I was thinking that either the links be hard typed with https:// or we handle that, but I will change the implementation for us to handle it.

2024-05-03 05:45 UTC, ConnorWon approved these changes

2024-05-03 05:46 UTC, merged