setup PR template + linter + lint check workflow
UBC-VCL/VCL-content-platform pull request #31
Opened 2022-09-22 03:02 UTC by kumarpit

- This is the PR template that will show up whenever a new PR is opened:
## Description

[Please enter a brief description of the PR]

## Updates

[Please enter a brief summary of updates to this PR during code review - if any]

## Checklist

- [ ] Ran `npm run lint:fix` to format code
- [ ] Connected PR to Trello ticket (steps below)
- [ ] Requested at least one reviewer

Connecting your PR to the corresponding ticket:
You will see a "GitHub" button on the right side of your ticket, click this -> Attach PR -> VCL-content-platform-server -> find your PR from the dropdown.

- Installed and configured ESLint. Just specified indent and quotation rules, extremely barebones at the moment. More rules can be added once we discuss what code style everyone agrees upon.

- Setup a workflow just to check if the current PR is correctly linted. Can add build checks to this as well. Let me know.

2022-09-22 03:04 UTC, kumarpit commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create Github Actions flow](https://trello.com/c/qE55EKFL/65-create-github-actions-flow)

2022-09-22 04:42 UTC, svolterra commented on .github/pull_request_template.md
> +You will see a "GitHub" button on the right side of your ticket, click this -> Attach PR -> VCL-content-platform-server -> find your PR from the dropdown.
I really like this template! Great work! Below are just a few suggestions for lines 11-16:
1. I moved the second point of the checklist to be right above the **Connecting your PR to the corresponding ticket** just for immediate access to the steps once you scroll down. 
2. Changed  **Connecting your PR to the corresponding ticket** to a header (can be any heading level but preferably not header level 1).
3. Changed the steps for connecting your PR to be a list instead. 

```suggestion
- [ ] Ran `npm run lint:fix` to format code
- [ ] Requested at least one reviewer
- [ ] Connected PR to Trello ticket (steps below)

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown. 
```

2022-09-22 04:44 UTC, svolterra commented on .github/pull_request_template.md
> +You will see a "GitHub" button on the right side of your ticket, click this -> Attach PR -> VCL-content-platform-server -> find your PR from the dropdown.
Perhaps we can also add the following to the checklist just in case? 
- [ ] Addressed code review comments
- [ ] Gained at least one approval for your PR

Up to you though :)

2022-09-22 05:22 UTC, svolterra requested changes

2022-09-22 05:22 UTC, svolterra commented on .github/workflows/node.js.yml
> +    branches: [ main ]
Hmm it seems this will only run the workflow when there are pushes specific to your current branch. What do you think of this approach instead? 

```suggestion
on: push
```
This seems to be all-encompassing as per [the docs](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow): 

> a workflow with the following on value will run when a push is made to any branch in the workflow's repository

2022-09-22 05:24 UTC, kumarpit commented on .github/workflows/node.js.yml
> +    branches: [ main ]
my bad, I had it set to my branch for testing

2022-09-22 05:25 UTC, kumarpit commented on .github/pull_request_template.md
> +You will see a "GitHub" button on the right side of your ticket, click this -> Attach PR -> VCL-content-platform-server -> find your PR from the dropdown.
sounds good, I'll add these

2022-09-22 05:35 UTC, svolterra commented on .github/workflows/node.js.yml
> +      - run: npm run lint
Would it be possible to add another job that runs before linting to ensure that the project builds successfully? Such as adding something similar to this before the `run_eslint` job? 

```
build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
```

2022-09-22 05:48 UTC, svolterra commented on .github/workflows/node.js.yml
> +      - run: npm run lint
Note: this does not have to be done in this PR :) Just asking if it is possible. If so, perhaps we can create a ticket for it.

2022-09-23 03:13 UTC, ElisaHu1 commented on .github/workflows/node.js.yml
> +      - run: npm run lint
Do we want to run es-lint first or run build first? From previous course work, if we do have a linting issue, the code cannot even be allowed to run

2022-09-23 20:03 UTC, svolterra commented on .github/workflows/node.js.yml
> +      - run: npm run lint
Ah yes :) Please refer to Elisa's comment above @kumarpit in regards to the proposed order of the jobs.

2022-09-26 03:06 UTC, ElisaHu1 commented
this looks great! Approved!

2022-09-26 03:06 UTC, ElisaHu1 approved these changes

2022-09-28 02:35 UTC, svolterra approved these changes
Thanks for addressing our CR comments!

2022-10-26 20:53 UTC, merged