Fixed Home, About and Project page layout on small screens
UBC-VCL/VCL-content-platform pull request #39
Opened 2022-11-17 23:12 UTC by Taosit

Made many changes to prevent overflow and make the layout more consistent. The 3 pages are now responsive on mobile and tablet

## Description

<img width="216" alt="home" src="https://user-images.githubusercontent.com/87669275/202577657-0600083a-3126-481e-84b4-a0349cdfc861.png">
<img width="216" alt="projects" src="https://user-images.githubusercontent.com/87669275/202577720-b8559b0e-8fb2-4e65-8bc5-58cdc8e4d8eb.png">
<img width="220" alt="about1" src="https://user-images.githubusercontent.com/87669275/202577727-a6916c7b-04c2-45ad-823f-0734cdfe0194.png">
<img width="217" alt="about2" src="https://user-images.githubusercontent.com/87669275/202577758-2b708b49-6d22-4844-a839-897100df9ed6.png">
<img width="213" alt="about3" src="https://user-images.githubusercontent.com/87669275/202577776-f972f1a2-2ed9-45d4-9a67-f9a69b251fde.png">

- Solved overflow issues;
- Changed absolute units (px) to relative units (%) for width, margin and padding in various components and pages;
- Added media queries for tablets (max-width: 1023px) and mobile (max-width: 767px). Changed max-width: 1024px to max-width: 1023px in existing code in various components and pages;
- Ajusted margin and padding values for consistency. Synced values of the same tags. Changed some values to be multiples of 4 or 8;
- Switched flexbox for grid in project page so that each project is centered in its allocated space;

## Updates

[Please enter a brief summary of updates to this PR during code review - if any]

## Checklist

- [x] Ran `npm run lint:fix` to format code
- [x] Requested at least one reviewer
- [x] Connected PR to Trello ticket (steps below)
- [ ] Addressed code review comments
- [ ] Gained at least one approval for your PR

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown.

2022-11-17 23:12 UTC, Taosit commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix the layout on mobile and tablet in home, about and project page](https://trello.com/c/uxNkzS5s/81-fix-the-layout-on-mobile-and-tablet-in-home-about-and-project-page)

2022-11-22 03:09 UTC, svolterra commented on src/components/Footer/Footer.tsx
> +                        <div className="footer-image-container">
Maybe a mishap from my end but I can't seem to find this newly added class in the css?

2022-11-22 03:13 UTC, svolterra commented on src/components/MissionStatement/MissionStatement.css
> +        padding: 16px 5% 48px;
Just wondering why you changed from % to px as a measuring unit?

2022-11-22 03:22 UTC, svolterra commented on src/components/MissionStatement/MissionStatement.css
> +        padding: 16px 5% 48px;
Also with these changes here the gap between the footer divider and the text is greatly reduced: 

  With your changes the footer looks like so:

<img width="1406" alt="Screen Shot 2022-11-21 at 7 15 42 PM" src="https://user-images.githubusercontent.com/71746168/203213060-daf14eb9-fae0-450b-b0ae-ebe71e5b2600.png">

While the Figma design differs in the margin between the divider and text:
<img width="927" alt="Screen Shot 2022-11-21 at 7 17 34 PM" src="https://user-images.githubusercontent.com/71746168/203213234-0aa4a632-0e09-41e5-bce3-f4022c091238.png">

As well, the width of the horizontal line increases in your changes which goes against the design.

2022-11-22 03:24 UTC, svolterra commented on src/components/MissionStatement/MissionStatement.tsx
> +        <div className="footer-divider"></div>
Interesting change! I do wonder why you chose `<div>` specifically here 🤔 I believe the `<hr>` tag gives a clearer identification of the element being added here. As in, it's crystal clear that there is a divider being added above the paragraph `<p>` text. More than happy to hear your point of view though!

2022-11-22 03:30 UTC, svolterra commented on src/pages/Home/Home.css
> +}
Hmm can you please change the name of the class name here? `some-section` seems to be quite vague.

2022-11-22 03:33 UTC, svolterra commented on src/pages/Home/Home.css
> +    background-color: #7C9DAF;
Please change the color to match the Figma design:

```suggestion
    background-color: #77B0F3;
```

2022-11-22 03:46 UTC, svolterra commented on src/pages/Project/Project.css
> +    /* overflow: hidden; */
Please remove if it's not being used.

2022-11-22 03:48 UTC, svolterra commented on src/pages/Project/ProjectOverview.css
> +    margin-bottom: 32px;
Can you please explain why you decided to make this change? :)

2022-11-22 03:56 UTC, svolterra commented on src/pages/Project/ProjectOverview.css
> +    margin: 0 auto;
This deletes the space between the navbar and the project overview title, hence rendering something like this on mobile:

<img width="200" alt="Screen Shot 2022-11-21 at 7 49 58 PM" src="https://user-images.githubusercontent.com/71746168/203217213-d33d70fe-0841-4a55-bef3-265d869ad65d.png">

To add, this compresses the section on normal view.

2022-11-22 03:56 UTC, Taosit commented on src/App/App.css
> +}
My fault. Never bothered with commented stuff. Will change it

2022-11-22 04:04 UTC, svolterra commented on src/pages/Project/ProjectOverview.css
> +    height: 2px;
This height is quite thick, perhaps a `1px` or `0.5px` would match the design more closely?

2022-11-22 04:05 UTC, Taosit commented on src/components/MissionStatement/MissionStatement.css
> +        padding: 16px 5% 48px;
I changed this mainly because I don't want to have a mixture of margins and paddings that serve roughly the same purpose. As for the unit, I don't know. Mostly I just go for px, especially multiples of 4 to make it more neat. I just feel like there's more control with px when it comes to smaller values. But I guess I'm not always that consistent. Let's learn more and get better together!

Yeah sorry for deviating from the design. My screen is smaller so it kind of look ok on my screen, but I should have checked with larger screen sizes. I'll change it. The difference in the width of the line is also because of the screen size. I'm not very concerned about the absolute length. As screen size changes I would expect it to change as well

2022-11-22 04:06 UTC, svolterra commented on src/components/Footer/Footer.css
> -}
Please don't forget to remove references to this class in the `.tsx` file as well if it is to be deleted.

2022-11-22 04:10 UTC, Taosit commented on src/components/MissionStatement/MissionStatement.tsx
> +        <div className="footer-divider"></div>
Well it's just because I'm not used to using <hr>. I know it would work with div if we give it a background color. In this case, I don't have to use border-bottom, which may mean it also has a width that I'm not actively controlling. It may work with <hr> with a different property but as I said I'm not very familiar with <hr>

2022-11-22 04:13 UTC, Taosit commented on src/pages/Home/Home.css
> +}
The web page is not complete. The card content is very generic so I'm not sure what section it's in. The only thing I know is that it's in some section. So I left it as that, thinking that I'll give it a more meaningful name once there's more context.

2022-11-22 04:14 UTC, Taosit commented on src/pages/Home/Home.css
> +    background-color: #7C9DAF;
Ok, I must have copied the wrong thing

2022-11-22 04:18 UTC, svolterra commented
Hi Jingxuan, just a few general comments on your PR! 

1. Your code demonstrates attention to detail when it comes to code cleanliness, so well done!
2. Usually it is best to follow the single responsibility rule even in PRs, in which you focus on one specific problem area per PR, not all at once. This is recommended such that the reviewer doesn't get overwhelmed with large amounts of code all at once, and due to the increased likelihood of the code contributor making mistakes when the PR is large.
3. While I do appreciate your initiative and passion, I personally do not think that some files needed to be changed, as the changes made them stray from the design they once followed more strictly. As such, I do hope you understand when I oppose the changes made to some of the files modified in this PR.

All in all, good work. I admire your passion and your knowledge of CSS.

2022-11-22 04:19 UTC, Taosit commented on src/pages/Project/ProjectOverview.css
> +    margin-bottom: 32px;
Currently with flex-wrap there can be a big margin on the right side of the flex container. Grid is more rigorous compared to flex. It puts each item to its allocated space while allows us to specify its position within the its space if it's not occupying the entire space. I'm thinking perhaps we should make it expand the entire space since there's a reasonable upper limit anyways

2022-11-22 04:22 UTC, Taosit commented on src/pages/Project/ProjectOverview.css
> +    height: 2px;
Sure I'll change the mobile view to 1px

2022-11-22 04:23 UTC, svolterra commented on src/components/Footer/Footer.css
> -}
For the changes made here, since we already have an open task for fixing the footer, I suppose the changes belong better there.

Since I have picked up that task and created a PR for it, I will look into addressing your code review comments and integrating the changes you have done here such that we can have a co-operative bug-fixing pull request. 

As such, please revert the changes to this class at the moment for this PR. This can be done by running the following command:

`git checkout main src/components/Footer/Footer.css`

2022-11-22 04:29 UTC, svolterra commented on src/components/MissionStatement/MissionStatement.tsx
> +        <div className="footer-divider"></div>
That's okay! Since we are all learning, please look into the `<hr>` tag and let me know what you think about it.

2022-11-22 04:32 UTC, svolterra commented on src/pages/Home/Home.css
> +}
How about the name `card-section` or `home-section` for the time-being?

2022-11-22 04:36 UTC, svolterra commented on src/pages/Project/ProjectOverview.css
> +    height: 2px;
Not just in mobile view please as it currently looks like this on normal view:

<img width="1083" alt="Screen Shot 2022-11-21 at 8 32 14 PM" src="https://user-images.githubusercontent.com/71746168/203222529-6ba01ca5-3e20-4163-99fd-be3336e5b737.png">

When it should look like:

<img width="809" alt="Screen Shot 2022-11-21 at 8 32 52 PM" src="https://user-images.githubusercontent.com/71746168/203222616-d50bb66a-5922-4071-84b2-ed96d663edb7.png">

2022-11-22 04:40 UTC, svolterra requested changes
@Taosit, just a few general comments on your PR!

1. Your code demonstrates attention to detail when it comes to code cleanliness, so well done!
2. Usually it is best to follow the single responsibility rule even in PRs, in which you focus on one specific problem area per PR, not all at once. This is recommended such that the reviewer doesn't get overwhelmed with large amounts of code all at once, and due to the increased likelihood of the code contributor making mistakes when the PR is large.
3. While I do appreciate your initiative and passion, I personally do not think that some files needed to be changed, as the changes made them stray from the design they once followed more strictly. As such, I do hope you understand when I oppose the changes made to some of the files modified in this PR.

All in all, good work. I admire your passion and your knowledge of CSS.

2022-11-22 04:47 UTC, svolterra commented on src/pages/Project/ProjectOverview.css
> +    margin-bottom: 32px;
Sounds good!

2022-11-22 04:48 UTC, svolterra commented on src/components/Footer/Footer.tsx
> +                        </div>
Please refer to [this comment ](https://github.com/UBC-VCL/VCL-content-platform/pull/39/files#r1028814399) as well regarding the `Footer` classes.

2022-11-22 04:53 UTC, svolterra commented on src/pages/About/About.css
> +}
Nice! Please add some space between the header and sub-header though as they are very close at the moment.

2022-11-22 04:56 UTC, svolterra commented on src/pages/About/About.css
> +    list-style: none;
Please remove the `list-style: none` line as it is removing the bullet points from the contacts information :

<img width="472" alt="Screen Shot 2022-11-21 at 8 52 04 PM" src="https://user-images.githubusercontent.com/71746168/203225112-3f114b73-c59b-4fbf-965f-48dd948ef39c.png">

2022-11-22 20:01 UTC, Taosit commented on src/pages/Project/ProjectOverview.css
> +    margin: 0 auto;
I just took a look at the element inspector and realized that the problem is not caused by margin 0. The navbar has a bottom margin of 35px and that's where the space on desktop comes from. However, the navbar is overflowing on mobile taking up all the space for the margin. We can perhaps try fixing the navbar first. (There is also some horizontal overflow which makes the navbar content not centre aligned)

2022-11-22 20:06 UTC, Taosit commented on src/components/Footer/Footer.css
> -}
Sounds good! It's reverted.
Are you also going to do the navbar?

2022-11-22 20:12 UTC, Taosit commented on src/components/MissionStatement/MissionStatement.tsx
> +        <div className="footer-divider"></div>
I changed this back to hr. I looked it up and here's what I found. Its color can be set by the attribute color. It has 4 borders by default and it's slightly going into the page. Since this is undesirable in our case, I also set the border to none

2022-11-22 22:59 UTC, Taosit commented on src/pages/About/About.css
> +    list-style: none;
I added more specificity and the bullet points are back
I think that's about all the changes I need to make in this pr. Since I reverted the footer, the 100vw problem is back for now. If you want to test your branch, you can bring those changes to your branch. Once the bug with the footer is fixed, there won't be any horizontal scrolling on mobile

2022-11-24 05:06 UTC, ElisaHu1 reviewed
a few issues I noticed when I test it locally
1. there is some white padding when I open the mobile page (happens to other pages as well)
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/104804980/203697980-2a167503-ddd0-4c0b-9628-a517e67b1fa1.png">
2. after I click the menu bar, white space is gone but the header is not aligned anymore 
<img width="923" alt="image" src="https://user-images.githubusercontent.com/104804980/203698156-7e0b49c4-d82e-453f-8769-fdce3b4c172a.png">
3. after I clicked login 
<img width="897" alt="image" src="https://user-images.githubusercontent.com/104804980/203698691-1863fb21-e416-410f-ab23-d82eafa97743.png">

4 the what can you gain sector is not aligned with the design anymore, and the background is constraint
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/104804980/203698378-049b5b5a-5190-4b35-9541-4ac2882f75f2.png">
compare to the original design 
<img width="511" alt="image" src="https://user-images.githubusercontent.com/104804980/203698479-5561e123-4d8a-45e4-b6b5-81e9e7f2e551.png">

2022-11-24 05:18 UTC, Taosit commented
Hi Elisa! Thanks for the review! Actually the margin issue you mentioned in 1, 2 and 3 are caused by the footer. Since Sara had another pr about the footer, she asked me to revert my changes on the footer. So the footer is still buggy in this pr request.  If you comment out the footer, the right margin will disappear and problem 1, 2 and 3 will go away too. (The navbar is overflown too, so it won't be perfectly centered. That'll be another pr.)

Thanks for pointing out the background in the card section. I totally overlooked it. I'll correct it soon

2022-11-25 18:39 UTC, Taosit commented
I merged the main branch to this branch and made a few minor changes. Please check the commit description for details.

2022-11-30 05:02 UTC, ElisaHu1 approved these changes
this looks great! I also merged Sarah's project nav bar to master, probably you can pick that in your pr (if there is a conflict)

2022-11-30 20:36 UTC, svolterra approved these changes
LGTM! Thanks!

2022-11-30 22:24 UTC, merged