Eason/#107 connect delete icon
UBC-VCL/VCL-content-platform pull request #79
Opened 2023-06-19 01:17 UTC by WYC401

## Description

[Please enter a brief description of the PR]

## Updates

[Please enter a brief summary of updates to this PR during code review - if any]

## Checklist

- [ ] Ran `npm run lint:fix` to format code
- [ ] Requested at least one reviewer
- [ ] Connected PR to Trello ticket (steps below)
- [ ] Addressed code review comments
- [ ] Gained at least one approval for your PR

## Connecting your PR to the corresponding ticket:
- Click on the "GitHub" button found on the right of your Trello ticket
- Choose "Attach PR" from the dropdown list
- Link your GitHub account (if you haven't done so already)
- Navigate to`VCL-content-platform` and choose your PR from the dropdown.

2023-06-19 01:17 UTC, WYC401 commented
![](https://github.trello.services/images/mini-trello-icon.png) [connect delete icon with backend](https://trello.com/c/j3SARKYx/107-connect-delete-icon-with-backend)

2023-06-19 18:30 UTC, ElisaHu1 commented on package.json
> -    "start": "export SET NODE_OPTIONS=--openssl-legacy-provider && react-app-rewired start",
can you revert this change since most people need to export

2023-06-19 18:31 UTC, ElisaHu1 commented on package.json
> +    "eslint": "7.11.0",
why you are adding eslint?

2023-06-19 18:31 UTC, ElisaHu1 commented on package-lock.json
can you delete the change for package-lock since it is autogenerated?

2023-06-19 18:53 UTC, ElisaHu1 commented
no functional problem:
anonymous user: see delete button but fail to delete
login user: successful delete, db change as well

2023-06-20 06:40 UTC, svolterra reviewed
Looks good Eason! Just left a few comments for clarification and styling purposes but really great work overall 🥳 🏆  Please also address @ElisaHu1's comments :) Thanks! 🎉

2023-06-20 06:40 UTC, svolterra commented on src/components/ConfirmationWindow/confirmationWindow.tsx
> +    const { onClose, open, deleteSnapshot } = props;
It seems here you are re-declaring the props you have already declared in `SimpleDialogProps` (`open`, `onClose`, `deleteSnapshot`). 

Instead of redeclaring them, you can access them in the body of the function by calling `props.open`, `props.onClose`, and `props.deleteSnapshot` instead. 

Additionally you can go with the following declaration instead and access the props directly the way you are doing here:
`function ConfirmationDailog({open, onClose, deleteSnapshot}: SimpleDialogProps) {`

2023-06-20 06:40 UTC, svolterra commented on src/components/ConfirmationWindow/confirmationWindow.tsx
> +  export default ConfirmationDailog;
For the sake of consistency, can you please rename this .tsx file and its corresponding .css file to `ConfirmationWindow` instead of `confirmationWindow` as all components currently follow this pattern of naming :)

2023-06-20 06:40 UTC, svolterra commented on src/components/TimelineCommitBlock/TimelineCommitBlock.tsx
> +    categories: Array<string>;
Hmm is there a specific reason you moved the `categories` prop to the bottom here? 🤔

2023-06-20 06:40 UTC, svolterra commented on src/components/TimelineCommitBlock/TimelineCommitBlock.tsx
> +    onClickDelete: () => void
Would it be possible to create a separate function for `onClickDelete` instead of making it a prop? 🤔 Just so we don't have to pass this in every time we declare a `TimelineCommitBlock`.

2023-06-20 06:40 UTC, svolterra commented on src/pages/Timeline/Timeline.tsx
> +      })
Can you please walk me through this code snippet? From what I understand, you're making a copy of the `commitsArray`, deleting the entry at the index of the snapshot we'd like to delete, then setting this new array as the new commitsArray? 

What happens if you don't include this block of code (for my information)? :) 

May there perhaps be another way to approach updating the commitsArray? Such as sending a GET request to the snapshots endpoint after the snapshot is successfully deleted and returns with a 200 status code?

2023-06-20 14:25 UTC, WYC401 commented on package.json
> +    "eslint": "7.11.0",
I will revert it back if all the technical issues in this pr are solved

2023-06-20 14:25 UTC, WYC401 commented on package-lock.json
I will revert it back if all the technical issues in this pr are solved

2023-06-20 14:26 UTC, WYC401 commented on src/components/ConfirmationWindow/confirmationWindow.tsx
> +const emails = ["username@gmail.com", "user02@gmail.com"];
This is just a stupid copy and paste. Have deleted it

2023-06-20 14:27 UTC, WYC401 commented on src/components/ConfirmationWindow/confirmationWindow.tsx
> +  export default ConfirmationDailog;
Have renamed it

2023-06-20 14:27 UTC, WYC401 commented on src/components/TimelineCommitBlock/TimelineCommitBlock.tsx
> +    categories: Array<string>;
Hmmm, I just get used to append fields which are newly changed. So which order should I put these fields by

2023-06-21 02:42 UTC, ElisaHu1 commented on package.json
> -    "start": "export SET NODE_OPTIONS=--openssl-legacy-provider && react-app-rewired start",
yes, sounds good to me

2023-06-21 02:43 UTC, ElisaHu1 approved these changes
i will approve it now, but remember to revert your package.json

2023-06-21 06:06 UTC, svolterra commented on src/components/TimelineCommitBlock/TimelineCommitBlock.tsx
> +    categories: Array<string>;
Oh then perhaps can you just undo this change then just to be consistent across the files with the ordering of the props :)

2023-06-21 06:07 UTC, svolterra commented on src/components/TimelineCommitBlock/TimelineCommitBlock.tsx
> +    onClickDelete: () => void
I think we can leave it as is for now! :)

2023-06-21 06:07 UTC, svolterra commented on src/pages/Timeline/Timeline.tsx
> +      })
I see! Makes sense :) Thanks!

2023-06-21 06:10 UTC, svolterra requested changes
LGTM thanks! Great work Eason! But please revert your changes to `package.json` and remove the addition of `package-lock.json` from your PR before merging. I will request changes for this as it can cause nasty merge conflicts but otherwise looks good to me :) 👏  Once you've done that feel free to merge.

2023-06-22 00:34 UTC, WYC401 commented
> LGTM thanks! Great work Eason! But please revert your changes to `package.json` and remove the addition of `package-lock.json` from your PR before merging. I will request changes for this as it can cause nasty merge conflicts but otherwise looks good to me :) 👏 Once you've done that feel free to merge.

I have reverted package.json and package-lock.json by copying and pasting the same files in main branch

2023-06-23 04:36 UTC, ElisaHu1 commented
> the

your package.json is still different from the main, can you delete it?

2023-06-23 04:42 UTC, WYC401 commented
> > the
> 
> your package.json is still different from the main, can you delete it?

<img width="1498" alt="image" src="https://github.com/UBC-VCL/VCL-content-platform/assets/90591280/8cefa063-1ce6-4022-a556-addc597b777f">
Did you refresh the page? I only see a very dummy change in package-lock.json in which the addition and deletion have been cancelled out

2023-06-23 04:50 UTC, ElisaHu1 commented
> > > the
> > 
> > 
> > your package.json is still different from the main, can you delete it?
> 
> <img alt="image" width="1498" src="https://user-images.githubusercontent.com/90591280/248154901-8cefa063-1ce6-4022-a556-addc597b777f.png"> Did you refresh the page? I only see a very dummy change in package-lock.json in which the addition and deletion have been cancelled out

can you fix the merge conflict?

2023-06-26 08:30 UTC, svolterra approved these changes
LGTM! Thanks for your great work! 🏆

2023-06-26 18:51 UTC, merged